// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obzfcrbvdpnundexzepd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9iemZjcmJ2ZHBudW5kZXh6ZXBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1OTc4MzksImV4cCI6MjA1OTE3MzgzOX0.g5fnwTlHvYwKe8CmarNSkcf8ojr_M-Qoa23Czt0iJTc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);